-- Add new values to ResearchActivityType enum
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'RESEARCH_PAPER';
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'JOURNAL_ARTICLE';
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'CONFERENCE_PAPER';
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'WORKING_PAPER';
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'TECHNICAL_REPORT';
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'BOOK_CHAPTER';
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'DATASET_RELEASE';
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'TEACHING';
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'SUPERVISION';
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'COLLABORATION';
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'PATENT';
ALTER TYPE "ResearchActivityType" ADD VALUE IF NOT EXISTS 'SOFTWARE_RELEASE';
